### ISSUE TITLE
"For You" section returns CONTENT_UNAVAILABLE

### ISSUE THREAD

**Issue by DannyDannyDanny** [falcon78/Vusic#13]
First off; I love the web player!

This might be some external dependency or a breaking change on Apple's side. Either way I cannot load the "For You" section.

I tried in FF and Chrome:
* Mozilla Firefox 78.5.0esr (64-bit)
* Google Chrome 87.0.4280.88 (Official Build) (64-bit)

Both browsers show this message when clicking "For You":
![image](https://user-images.githubusercontent.com/16453674/102368074-c23a4e00-3fba-11eb-92a3-cbc8578eafe4.png)

**Comment by falcon78** [comment]
Huh that's weird. Looks like something has changed with the api maybe. I'll see if there is any alternative endpoint i can query. Thank you for opening the issue and letting me know!

**Comment by DannyDannyDanny** [comment]
Since I opened the issue, I've noticed its appearance is inconsistent. I can't reproduce it, but it is working today. I have a feeling it might be something cookie related.

**Comment by falcon78** [comment]
Looks like it's working for me too, I'll close this issue for now and see if it happens again. Thanks for reporting!
